kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgsql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: <default storage class name for cluster you are deploying on>
  volumeMode: Filesystem